<?php
/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */

if ( !class_exists( 'ReduxFramework' ) && file_exists( dirname( __FILE__ ) . '/Redux/framework.php' ) ) {
    require_once( dirname( __FILE__ ) . '/Redux/framework.php' );
}
require_once( get_template_directory()  . '/functions/admin-config.php' );
require_once ( get_template_directory() . '/functions/functions.php' );
require_once ( get_template_directory() . '/functions/hooks.php' );
require_once ( get_template_directory() . '/functions/function-extras.php' );

if ( ! function_exists('bi_option') ) {
	function bi_option($id, $fallback = false, $param = false) {
		global $bi_option;
		if ( $fallback == false ) $fallback = '';
		$output = ( isset($bi_option[$id]) && $bi_option[$id] !== '' ) ? $bi_option[$id] : $fallback;
		if ( !empty($bi_option[$id]) && $param ) {
			$output = $bi_option[$id][$param];
		}
		return $output;
	}
}

add_theme_support( 'custom-background');

require_once( get_template_directory() .'/functions/google-fonts.php' );
require_once( get_template_directory() .'/functions/custom-css.php' );
require_once( get_template_directory() .'/functions/tracking.php' );
require_once( get_template_directory() .'/functions/meta.php' );

// Functions needed for admin
require_once( get_template_directory() .'/functions/post-types/post-type-helpers.php' );
require_once( get_template_directory() .'/functions/post-types/register-post-types.php' );
require_once( get_template_directory() .'/functions/post-types/register-taxonomies.php' );

/************* METABOX ****************/

// Re-define meta box path and URL
define( 'RWMB_URL', trailingslashit( get_stylesheet_directory_uri() . '/functions/meta-box' ) );
define( 'RWMB_DIR', trailingslashit( TEMPLATEPATH . '/functions/meta-box' ) );
// Include the meta box script
require_once RWMB_DIR . 'meta-box.php';
require_once RWMB_DIR . 'setup.php';

